export type {
  ThemeId,
  ThemeMode,
  ThemeDefinition,
} from '@/stores/settingsStore';
export type {
  AppInfo,
  BaselineComparison,
  BootstrapStatus,
  ConflictHint,
  DiagnosticsSummary,
  ExportPayload,
  IdleReport,
  KeybindComboPart,
  KeybindOverride,
  LogLine,
  MaterializedWorkspace,
  MetricDelta,
  MetricDirection,
  MultiSpawnReport,
  PaneOutputCounters,
  PassthroughEntry,
  PerfProbeResult,
  RecoveryStatus,
  SetKeybindOverrideResult,
  StateSnapshot,
  SystemHealth,
  TemplatePaneSpec,
  ThroughputReport,
  TtyRespondingProbeReport,
  UpdateInfo,
  WorkspaceSummary,
  WorkspaceTemplate,
} from '@/types/ipc';
export type {
  LayoutPreset,
  Workspace,
  WorkspacePane,
} from '@/types/workspace';
